0x53 MSTORE8
sayajin-labs/kakarot pull request #166
Opened 2022-10-26 22:51 UTC by danilowhk

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- 0x53 MSTORE8 opcode
-
-

## Other information

2022-10-26 22:53 UTC, abdelhamidbakhta approved these changes
Lgtm

2022-10-26 22:54 UTC, danilowhk commented
For some reason, I am getting "make format" error even though on my pc its showing that it doesn't have any

2022-10-26 22:57 UTC, abdelhamidbakhta commented
> For some reason, I am getting "make format" error even though on my pc its showing that it doesn't have any

Hmm, weird. Will check tomorrow

2022-10-26 22:59 UTC, danilowhk commented
Ok! The last one that this happened, Lucas merged into another branch and then made the PR. But it did request for him to run "make format", could it be that my "make format" is formatting in a different way? As there are some changes in this PR that I didn't do. But overall it's a small thing hehe

2022-10-27 09:11 UTC, LucasLvy requested changes

2022-10-27 09:11 UTC, LucasLvy commented on src/kakarot/memory.cairo
> +        assert [new_memory + offset] = element.low;
```suggestion
        assert [new_memory + offset] = element;
```

2022-10-27 09:17 UTC, danilowhk commented on src/kakarot/instructions/memory_operations.cairo
> +        let memory: model.Memory* = Memory.store8(self=ctx.memory, element=remainder, offset=offset.low);
If we use just the value instead of remainder, i think it would filter the first byte

2022-10-27 13:16 UTC, closed without merging