Feat/add 0x47 SELFBALANCE opcode
sayajin-labs/kakarot pull request #174
Opened 2022-10-27 14:36 UTC by ftupas

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #87
Fixes: #87

## What is the new behavior?

- 0x47 SELFBALANCE opcode implemented
- Get balance of currently executing account by getting `caller_address` and querying its balance from the eth contract

## Other information

2022-10-27 16:25 UTC, LucasLvy commented
The current contract address will most likely be passed in a call context. The caller address won’t be the self address

2022-10-27 16:52 UTC, LucasLvy requested changes
Format and rebase please

2022-10-27 17:32 UTC, ftupas commented
> The current contract address will most likely be passed in a call context. The caller address won’t be the self address

Thanks for your feedback @LucasLvy 🤝 Got it let me change that

2022-10-28 09:55 UTC, LucasLvy requested changes

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/execution_context.cairo
> +        current_contract_address: Uint256*, code: felt*, code_len: felt, calldata: felt*
Ethereum address is 20 bytes and starknet address is a felt so they both fit in a felt
```suggestion
        current_contract_sn_address: felt, code: felt*, code_len: felt, calldata: felt*
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/execution_context.cairo
```suggestion
map current starknet address to evm address
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/execution_context.cairo
> +            current_contract_address=current_contract_address,
```suggestion
            self_sn_address=current_contract_sn_address,
            self_evm_address=mapped_sn_address,
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/execution_context.cairo
> +            current_contract_address=self.current_contract_address,
```suggestion
            self_sn_address=self.self_sn_address,
            self_evm_address=self.self_evm_address,
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/execution_context.cairo
> +            current_contract_address=self.current_contract_address,
```suggestion
            self_sn_address=self.self_sn_address,
            self_evm_address=self.self_evm_address,
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/execution_context.cairo
> +            current_contract_address=self.current_contract_address,
```suggestion
            self_sn_address=self.self_sn_address,
            self_evm_address=self.self_evm_address,
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/execution_context.cairo
> +            current_contract_address=self.current_contract_address,
```suggestion
            self_sn_address=self.self_sn_address,
            self_evm_address=self.self_evm_address,
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/execution_context.cairo
> +            current_contract_address=self.current_contract_address,
```suggestion
            self_sn_address=self.self_sn_address,
            self_evm_address=self.self_evm_address,
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/execution_context.cairo
> +            current_contract_address=self.current_contract_address,
```suggestion
            self_sn_address=self.self_sn_address,
            self_evm_address=self.self_evm_address,
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/execution_context.cairo
> +            current_contract_address=self.current_contract_address,
```suggestion
            self_sn_address=self.self_sn_address,
            self_evm_address=self.self_evm_address,
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/instructions/block_information.cairo
> +        let (registry_address_) = registry_address.read();
```suggestion
```
no need to map the address anymore

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/instructions/block_information.cairo
> +            contract_address=native_token_address_, account=starknet_address
```suggestion
            contract_address=native_token_address_, account=ctx.sn_address
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/kakarot.cairo
> +    current_contract_address_len: felt,
```suggestion
    sn_contract_address: felt,
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/kakarot.cairo
> +    current_contract_address: Uint256*,
```suggestion
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/kakarot.cairo
> +        current_contract_address=current_contract_address,
map sn_address to evm address and then
```suggestion
            self_sn_address=self.self_sn_address,
            self_evm_address=self.self_evm_address,
```

2022-10-28 09:55 UTC, LucasLvy commented on src/kakarot/library.cairo
> +        current_contract_address: Uint256*, code: felt*, code_len: felt, calldata: felt*
```suggestion
        sn_contract_address: felt, code: felt*, code_len: felt, calldata: felt*
```

2022-10-28 09:55 UTC, LucasLvy commented on tests/cairo_files/test_execution_context.cairo
>      let (calldata) = alloc();
same changes as everywhere

2022-10-28 09:56 UTC, LucasLvy commented
you probably don't have to do the changes everywhere but do it so we only have to map the address once

2022-10-28 10:53 UTC, ftupas commented
> you probably don't have to do the changes everywhere but do it so we only have to map the address once

Thanks for the review @LucasLvy 🙂 got it will do that so mapping is done only once

2022-11-05 07:47 UTC, Eikix commented on src/kakarot/execution_context.cairo
> +        sn_contract_address: felt,
what does sn stand for? starknet?

2022-11-05 07:54 UTC, Eikix requested changes
Hey @ftupas :), first of all thanks for your patience, you waited a long time for this PR to be merged
can you explain a bit why we need to add two inputs to the ExecutionContext? I did not understand your intent.

What I understood:
- you're hacking at Selfbalance, which is supposed to return the currently executing contract's own balance in native token
- why do you need to keep track of the starknet address of that contract as well as its evm representation in the execution context?

2022-11-05 09:50 UTC, ftupas commented
> Hey @ftupas :), first of all thanks for your patience, you waited a long time for this PR to be merged can you explain a bit why we need to add two inputs to the ExecutionContext? I did not understand your intent.
> 
> What I understood:
> 
>     * you're hacking at Selfbalance, which is supposed to return the currently executing contract's own balance in native token
> 
>     * why do you need to keep track of the starknet address of that contract as well as its evm representation in the execution context?

Hi there @Eikix , thanks for the review and feedback! Prior to the changes from the hackathon, my idea was to include both the starknet and evm contract addresses to the ExecutionContext so the mapping is done once and can be used by the opcodes i.e. getting the native token balance of the executing starknet contract address (mapped from the evm address).  However, I'm redoing this PR right now since the evm and starknet address mapping has been implemented [here](https://github.com/sayajin-labs/kakarot/blob/main/src/kakarot/execution_context.cairo#L100-L102).

2022-11-05 10:10 UTC, Eikix commented
> > Hey @ftupas :), first of all thanks for your patience, you waited a long time for this PR to be merged can you explain a bit why we need to add two inputs to the ExecutionContext? I did not understand your intent.
> > What I understood:
> > ```
> > * you're hacking at Selfbalance, which is supposed to return the currently executing contract's own balance in native token
> > 
> > * why do you need to keep track of the starknet address of that contract as well as its evm representation in the execution context?
> > ```
> 
> Hi there @Eikix , thanks for the review and feedback! Prior to the changes from the hackathon, my idea was to include both the starknet and evm contract addresses to the ExecutionContext so the mapping is done once and can be used by the opcodes i.e. getting the native token balance of the executing starknet contract address (mapped from the evm address). However, I'm redoing this PR right now since the evm and starknet address mapping has been implemented [here](https://github.com/sayajin-labs/kakarot/blob/main/src/kakarot/execution_context.cairo#L100-L102).

Hey @ftupas, thanks for your quick reply. I understand, I'd like to apologize for your troubles, we could've coordinated better.

Are you on the kakarot telegram group? If not, kindly provide your telegram handle and I'll add you. This way we'll make sure coordination and communication improves. I want to make sure this is the last time you have to go through all these hardships to merge a PR. Thanks again for your patience 🔥 🚀

2022-11-05 10:47 UTC, Eikix commented
> 

Hey @ftupas , after discussing with Lucas, you can still store starknet_contract_address and evm_contract_address in the execution context:)
Tell me when you're done with the changes you wanted to do, but as far as I'm concerned, your PR can be merged

2022-11-05 10:50 UTC, Eikix commented on src/kakarot/execution_context.cairo
> +            sn_address=sn_contract_address,
could we rename this starknet_contract_address or starknet_address to keep consistency in the repo?

2022-11-05 12:16 UTC, ftupas commented
> > > Hey @ftupas :), first of all thanks for your patience, you waited a long time for this PR to be merged can you explain a bit why we need to add two inputs to the ExecutionContext? I did not understand your intent.
> > > What I understood:
> > > ```
> > > * you're hacking at Selfbalance, which is supposed to return the currently executing contract's own balance in native token
> > > 
> > > * why do you need to keep track of the starknet address of that contract as well as its evm representation in the execution context?
> > > ```
> > 
> > 
> > Hi there @Eikix , thanks for the review and feedback! Prior to the changes from the hackathon, my idea was to include both the starknet and evm contract addresses to the ExecutionContext so the mapping is done once and can be used by the opcodes i.e. getting the native token balance of the executing starknet contract address (mapped from the evm address). However, I'm redoing this PR right now since the evm and starknet address mapping has been implemented [here](https://github.com/sayajin-labs/kakarot/blob/main/src/kakarot/execution_context.cairo#L100-L102).
> 
> Hey @ftupas, thanks for your quick reply. I understand, I'd like to apologize for your troubles, we could've coordinated better.
> 
> Are you on the kakarot telegram group? If not, kindly provide your telegram handle and I'll add you. This way we'll make sure coordination and communication improves. I want to make sure this is the last time you have to go through all these hardships to merge a PR. Thanks again for your patience 🔥 🚀

Thanks for your time to discuss and adding me to the telegram group @Eikix ! As discussed, I redid the PR to take into account the changes to way `ExecutionContext` is initialized (`init` and `init_at_address`). I've marked the test as skip for now and will unmark it once the testing architecture is changed 👍

Appreciate your feedback and reviews!

2022-11-05 14:48 UTC, ftupas commented on tests/test_zk_evm.py
> +        "marks": pytest.mark.execute_at_address,
Test cases with this mark will be tested with `test_execute_at_address`

2022-11-05 15:23 UTC, Eikix approved these changes

2022-11-05 15:24 UTC, LucasLvy approved these changes
didn't check

2022-11-05 15:26 UTC, merged