Memory.load n
sayajin-labs/kakarot pull request #288
Opened 2022-11-22 16:25 UTC by hurrikaanig

refactoring Memory.load to Memory.load_n to load n bytes from memory

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

https://github.com/sayajin-labs/kakarot/issues/287

Issue Number: 287

## What is the new behavior?

-
-
-

## Other information

2022-11-22 17:39 UTC, Eikix commented on src/kakarot/memory.cairo
> +            let res: Uint256 = Helpers.bytes_i_to_uint256(new_memory + offset, n, zero);
unrelated to your PR (in terms of scope) but why does `bytes_i_to_uint256` take in a third argument named res?

@LucasLvy any input:)?

2022-11-22 18:23 UTC, hurrikaanig commented on src/kakarot/memory.cairo
> +            let res: Uint256 = Helpers.bytes_i_to_uint256(self.bytes + offset, n, zero);
even in tests ?

2022-11-23 13:26 UTC, Eikix requested changes
1. After seeing with @LucasLvy, we have confirmation that the `res` argument in `bytes_i_to_uint256` is useless. Could you add a commit that deletes this argument and refactors code that uses it?

2. There is a comment in the helper's code `// Check if i si inferiour to 32`, could you fix the unfortunate typo introduced there (not by you)?


Very cool PR overall, thanks a lot:)
Will be good to go right after

2022-11-23 19:23 UTC, Eikix approved these changes
Nice PR 🔥!

2022-11-23 19:24 UTC, merged