precompile RIPEMD-160 + Tests
sayajin-labs/kakarot pull request #421
Opened 2023-01-08 02:51 UTC by hurrikaanig

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

no precompile RIPEMD-160

Resolves #<359>

## What is the new behavior?

precompile RIPEMD-160 :rocket:  

-
-
-

## Other information

Time spent on this PR:  1 day

2023-01-09 15:27 UTC, ClementWalter requested changes
can you add a test in `test_cases.py` ? otherwise we don't test that the right precompile is behind the right address.
You can copy/paste the test from the evm.playground

2023-01-09 15:27 UTC, ClementWalter commented on tests/unit/src/kakarot/precompiles/test_ripemd160.py
> +        ids=["calldata_len128"],
remove this

2023-01-09 17:47 UTC, hurrikaanig commented on src/kakarot/precompiles/ripemd160.cairo
> +func pow2(i : felt) -> (res : felt){
Sure I can do it

2023-01-11 15:05 UTC, ClementWalter approved these changes

2023-01-11 15:05 UTC, ClementWalter commented on tests/integration/bytecode/test_cases.py
> +            "stack": str(int("2c0c45d3ecab80fe060e5f1d7057cd2f8de5e557", 16)),
fyi, you can use
```
str(0x2c0c45d3ecab80fe060e5f1d7057cd2f8de5e557)
```

2023-01-11 15:11 UTC, ClementWalter commented
you need to rebase because the signature of the precompile has changed since https://github.com/sayajin-labs/kakarot/pull/404

2023-01-11 22:49 UTC, ClementWalter approved these changes

2023-01-11 22:49 UTC, ClementWalter commented on tests/integration/bytecode/test_cases.py
> +            "stack": str("0x2c0c45d3ecab80fe060e5f1d7057cd2f8de5e557"),
I guess that your previous `str(int(..))` was `str(0x...)` but without the quotes. In python, you can type `0xf` directly and it prints out (it is a) `15`

2023-01-11 22:49 UTC, ClementWalter commented on tests/unit/src/kakarot/precompiles/test_ripemd160.py
> +        message_bytes = bytes(message, encoding='utf8')
what about a `message_bytes = bytearray([random.randint(0,  255) for _ in range(len))`

2023-01-11 22:49 UTC, ClementWalter commented on tests/unit/src/kakarot/precompiles/test_ripemd160.py
> +        ripemd160_crypto = RIPEMD160.new()
could you just put this right before it's used for readability?

2023-01-12 07:40 UTC, ClementWalter approved these changes

2023-01-12 07:40 UTC, merged