feat: Add gas_used to kakarot.execute_at_address returned values
sayajin-labs/kakarot pull request #449
Opened 2023-01-20 15:55 UTC by mradolux

Time spent on this PR: 0.5 day

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

execute_at_address doesn't return gas_used

Resolves #<Issue number>

execute_at_address does return gas_used

- added gas used to return values of execute_at_address function

2023-01-20 16:23 UTC, ClementWalter requested changes
some tests are skipped because of this missing returned value, can you update them? (search for gas_used or gas_usage)

2023-01-22 16:10 UTC, mradolux commented
The failing test is not caused by the gas_used variable, it is caused by the createPair function. We can't test the gas_used variable before fixing the "StarknetErrorCode.OUT_OF_RESOURCES: 42" caused by the createPair

2023-01-23 12:44 UTC, ClementWalter commented
you should be able to pass tests updating the config given to `Starknet.empty(...)`

- in file `1_starknet.py`
- import `from starkware.starknet.definitions.general_config import StarknetGeneralConfig`
- right before `starknet = await Starknet.empty()` in the fixture
   - create a config `config = StarknetGeneralConfig(invoke_tx_max_n_steps=2**24, validate_max_n_steps=2**24)`
   - use this config `starknet = await Starknet.empty(config)`

2023-01-25 02:10 UTC, mradolux commented
The gas_used of the tx doesn't correspond to the value written in the test, should we update it or should the gas_used of the tx be equal to the value written in the test ?

2023-01-25 16:45 UTC, ClementWalter approved these changes

2023-01-25 19:37 UTC, mradolux commented on tests/integration/solidity_contracts/UniswapV2/test_uniswap_v2_factory.py
>              tx = await factory.createPair(
How can I activate the CI on my forked repo ?

2023-01-25 19:50 UTC, jobez commented on tests/integration/solidity_contracts/UniswapV2/test_uniswap_v2_factory.py
>              tx = await factory.createPair(
<img width="633" alt="image" src="https://user-images.githubusercontent.com/615197/214673764-b87d92f7-c34b-407d-a595-e30215a87b8c.png">

I think its just clicking a button prompt that shows up when you click the actions tab in your forked repo.

2023-01-25 19:58 UTC, mradolux commented on tests/integration/solidity_contracts/UniswapV2/test_uniswap_v2_factory.py
>              tx = await factory.createPair(
I think it's good now

2023-01-26 09:08 UTC, merged