UniswapV2Factory full test
sayajin-labs/kakarot pull request #471
Opened 2023-01-28 19:07 UTC by ClementWalter

Time spent on this PR: 0.5

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Token addresses are random instead the same one as in the original test.
Test using `createPair` is skipped

Resolves #467 

## What is the new behavior?

All tests pass as in the original file

2023-01-29 21:29 UTC, Eikix commented on src/kakarot/instructions/environmental_information.cairo
> +        let evm_address = (1 - is_root) * ctx.calling_context.evm_contract_address + is_root * current_evm_address;
nice catch!

2023-01-29 21:30 UTC, Eikix approved these changes
lgtm

2023-01-29 21:35 UTC, Eikix requested changes
Nvm I didn't notice tests were failing

2023-02-01 05:36 UTC, ClementWalter commented on src/kakarot/instructions/environmental_information.cairo
> +        let evm_address = (1 - is_root) * ctx.calling_context.evm_contract_address + is_root * current_evm_address;
tribute to @seshanthS actually

2023-02-01 05:42 UTC, ClementWalter commented
> Nvm I didn't notice tests were failing

It took me quite a lot of time to understand what was the issue. Actually the `ExecutionContext.is_root` and `ExecutionContext.is_leaf` (note: I wrote them myself two months ago) were not checking that a given _true_ context was root or leaf ; it was working only on the dummy `empty_ctx`.

These methods are not tested (!) and actually `is_root` was used only once with 

```
is_parent_root = ExecutionContext.is_root(ctx.calling_context);
```

which was quite misleading imao against past me. Consequently I've updated these helpers to be usable on the actual current execution context. For now, I've just considered that checking against an empty `evm_contract_address` was enough, wdyt?

2023-02-01 21:13 UTC, Eikix commented
> 

Are we still maintaining kakarot.execute?

It looked to me as though we were slowly deprecating kakarot.execute in favor of kakarot.execute_at_address

2023-02-03 07:37 UTC, merged