Legacy transaction support for Account Abstraction
sayajin-labs/kakarot pull request #478
Opened 2023-02-02 21:36 UTC by Flydexo

Added support for legacy transactions, see reference here:
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md
https://ethereum-magicians.org/t/eip-2718-typed-transaction-envelope/4355

Time spent on this PR: 3 days

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Legacy Transactions are refused by default

## What is the new behavior?

Legacy transactions are handled, verified.

2023-02-03 08:47 UTC, ClementWalter commented on src/kakarot/accounts/eoa/aa/library.cairo
> +        if (tx_type == 2) {
so `type = 2` introduces only a shift (3) in the indexes `V_IDX`, `R_IDX` and `S_IDX`. We could better just compute the correct indices and avoid the `if/else` and duplication.

```
let shift = tx_type / 2 * 3
let v_idx = V_IDX - shift
...
```

2023-02-03 09:05 UTC, TotalPizza commented
In general there are some more things we need to validate besides the signature:
Correct nonce, gasLimit is withing valid range, and a few more.
But it's probably best we do this with the TLV-Hackathon pr and not this one.

2023-02-03 15:46 UTC, Flydexo commented
> In general there are some more things we need to validate besides the signature: Correct nonce, gasLimit is withing valid range, and a few more. But it's probably best we do this with the TLV-Hackathon pr and not this one.

Yes, agree was starting for gas but the testing library doesn't allow spending gas on tx

2023-02-08 14:18 UTC, Eikix requested changes
What is the status of this PR after the TLV hacker house? 
@Flydexo @jobez @TotalPizza did anyone "fork" Flydexo's branch to complete this PR? Or is it still "relevant"?

2023-02-09 00:46 UTC, jobez commented
> What is the status of this PR after the TLV hacker house? @Flydexo @jobez @TotalPizza did anyone "fork" Flydexo's branch to complete this PR? Or is it still "relevant"?

I believe it is still relevant, as it extends the fork we were working with to add legacy support.

2023-02-13 08:27 UTC, closed without merging