refactor: eoa library file, remove unnecessary imports, use constants
sayajin-labs/kakarot pull request #527
Opened 2023-02-22 02:48 UTC by dragan2234

While working on the other task I noticed this library has some imports which are not used. I've run `test_eoa.py` and it's passing.

Time spent on this PR:

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves #<Issue number>

## What is the new behavior?

-
-
-

## Other information

2023-02-22 07:51 UTC, TotalPizza commented on src/kakarot/accounts/eoa/library.cairo
> +        if (call_array_len == FALSE) {
Imo in this scenario:
`call_array_len == 0` is preferable over `call_array_len == FALSE`,
As we're actually checking what the call_array length is and not whether it is true or false.

2023-02-22 10:26 UTC, ClementWalter requested changes
thx for the cleaning of the imports, we definitely miss such a tool in cairo format

2023-02-22 10:26 UTC, ClementWalter commented on src/kakarot/accounts/eoa/library.cairo
> +        if (call_array_len == FALSE) {
I'd keep this as "0" as we're comparing a len and not a bool

2023-02-23 10:19 UTC, ClementWalter approved these changes

2023-02-23 10:19 UTC, merged