Workshop: Add Function Comment
sayajin-labs/kakarot pull request #535
Opened 2023-02-24 17:04 UTC by makluganteng

I added some comment into the functions in src/kakarot/account/eoa/library.cairo. 

i work on this 1 day period.

Time spent on this PR: 1 day.

## Pull request type

Added function comment into src/kakarot/account/eoa/library.cairo.

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ X] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves #<Issue number> [#516]("https://github.com/sayajin-labs/kakarot/issues/516")

## What is the new behavior?

- Added comments to the code no behaviour change
-
-

## Other information

2023-02-25 19:01 UTC, ClementWalter requested changes
Thanks for your first PR!

For documentation, plz prefer descriptive syntax like
> @param a_param The X of Y

without extra verb ("takes in", etc.)

2023-02-25 19:01 UTC, ClementWalter commented on src/kakarot/accounts/eoa/library.cairo
> +    // @notice This function is to execute a function
Execute _transactions_ indeed

2023-02-26 14:11 UTC, makluganteng commented on src/kakarot/accounts/eoa/library.cairo
> +    // @param evm_address takes in EVM address.
is this the EVM contract address

2023-02-26 14:15 UTC, makluganteng commented on src/kakarot/accounts/eoa/library.cairo
> +    // @param evm_address takes in EVM address.
i mean the EVM address version of the kakarot address

2023-02-26 15:19 UTC, ClementWalter requested changes

2023-02-26 15:19 UTC, ClementWalter commented on src/kakarot/accounts/eoa/library.cairo
> +    // @param evm_address The EVM address version of the kakarot address.
I think that there is something unclear to you regarding the current kakarot architecture and consequently these parameters.
In the EVM, there are two types of accounts: Contract Account (smart contract) and Externally Owned Account (addresses controlled by wallets)
In kakarot, there is a smart contract deployed for each EVM address (see `IAccount` interface`). This contract, thus a Starknet contract, has a storage var `evm_address` to store the EVM address is contract is deployed for

2023-02-26 15:19 UTC, ClementWalter commented on src/kakarot/accounts/eoa/library.cairo
> +    // @notice Check if tx is signed and valid for each call and validate the transaction.
what does "validate" a tx means of not checking that the signature is valid? You could however give more details about how this is done:
- the whole EVM signed tx is given in the calldata
- it is rlp decoded, then message hash is computed and signature is checked against this hash (see `EthTransaction.validate` for more details)

2023-03-17 16:42 UTC, ClementWalter commented
@makluganteng would be able to finish the work?

2023-03-18 14:25 UTC, makluganteng commented
> 

yes i will, sorry iwasnt able to do it this past few weeks now ill try to finish the PR

2023-03-20 10:36 UTC, ClementWalter requested changes

2023-04-24 09:20 UTC, ClementWalter commented on src/kakarot/accounts/eoa/library.cairo
> +    // @param kakarot_address The address of the kakarot contract
`_kakarot_address`

2023-04-24 09:20 UTC, ClementWalter commented on src/kakarot/accounts/eoa/library.cairo
> +    // @param kakarot_address The address of the kakarot contract
`_evm_address`

2023-04-24 09:20 UTC, ClementWalter commented on src/kakarot/accounts/eoa/library.cairo
> +    // @param response The response.
The response data array to be updated

2023-04-24 09:20 UTC, ClementWalter commented on src/kakarot/accounts/eoa/library.cairo
> +    // @return response_len The length of the response.
The total length of the response data array

2023-04-24 14:40 UTC, ClementWalter commented
@makluganteng please fir your conflicts

2023-04-24 15:13 UTC, ClementWalter approved these changes

2023-04-26 15:05 UTC, merged